/** Autogenerated Main.cpp. */

// ================================| Include only the DSP files  |================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ==========================| Now we can add the rest of the codebase |==========================

#include <JuceHeader.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"

// ======================================| Project Factory |======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------------
		
		registerPolyNode<project::Tube2<1>, project::Tube2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ToVinyl4<1>, project::ToVinyl4<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ToTape5<1>, project::ToTape5<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::TexturizeMS<1>, project::TexturizeMS<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::TapeDust<1>, project::TapeDust<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Pockey2<1>, project::Pockey2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::GrooveWear<1>, project::GrooveWear<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Flutter<1>, project::Flutter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ClipSoftly<1>, project::ClipSoftly<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Band<1>, wrap::illegal_poly<project::Band<1>>>();
		registerDataNode<project::Test1_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#pragma clang diagnostic pop


