/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "ClipSoftly.h"
#include "Flutter.h"
#include "GrooveWear.h"
#include "Pockey2.h"
#include "TapeDust.h"
#include "TexturizeMS.h"
#include "ToTape5.h"
#include "ToVinyl4.h"
#include "Tube2.h"

// Include compiled network files ------------------

#include "Band.h"
#include "Test1_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

